sim.inputs:
  input_files:
  - ../hardware/src/normalize_clamp.sv
  - ../hardware/src/sliding_window.sv
  - ../hardware/src/window_dot_product.sv
  - ../hardware/src/window_dot_product_generic.sv
  - ../hardware/src/window_dot_product_5x5.sv
  - ../hardware/src/convolution_core.sv
  - ../hardware/src/conv_filter_top.sv
  - ../hardware/src/io_control_fsm.sv
  - ../hardware/src/kernel_register_array.sv
  - ../hardware/src/normalization_register.sv
  tb_input_files:
  - ../testbench/conv_filter_top/tb_conv_filter_top.sv
  - ../testbench/convolution_core/image_loader.sv
  - ../testbench/convolution_core/image_dumper.sv
  tb_defines:
  - TESTCASE_DIR=\"../../../testcases/3x3/emboss\"
  - KERNEL_SIZE=3
  - NORM_WIDTH=8
  - DATA_WIDTH=8
  - LINE_WIDTH=128
  - IMAGE_HEIGHT=128
  - NORMALIZATION_VALUE=128
  top_module: conv_filter_top
  tb_name: tb_conv_filter_top
  level: rtl
  options:
  - +vcs+vcdpluson
  - +vcs+vcdplusmemon
  - +vcs+vcdplusautoflushon
  - -sverilog
